apiVersion: v1
kind: Service
metadata:
  name: blog
  labels:
    app: blog
spec:
  selector:
    app: blog
  ports:
    - port: 80
      targetPort: 2368
      name: http
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: blog
  labels:
    app: blog
    env: production
    criticality: high
    build: "${TAG}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog
      env: production
      criticality: high
      build: "${TAG}"
  template:
    metadata:
      labels:
        app: blog
        env: production
        criticality: high
        build: "${TAG}"
    spec:
      volumes:
        - name: blog-data-production
          awsElasticBlockStore:
            volumeID: vol-0ce9108c5d285ffc2
            partition: 1
            fsType: ext4
      containers:
        - name: blog
          image: registry.repositive.io:5000/ghost:${TAG}
          volumeMounts:
            - mountPath: /var/lib/ghost
              name: blog-data-production
          resources:
            limits:
              cpu: 300m
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 100Mi
          ports:
            - containerPort: 2368
      imagePullSecrets:
        - name: regsecret
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: blog
  labels:
    app: blog
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  rules:
  - host: blog.repositive.io
    http:
      paths:
      - backend:
          serviceName: blog
          servicePort: 80
